# dependency for the host ansible is running on
---
- name: Dependency for the host ansible is running on
  hosts: ansible_host
  gather_facts: false
  tasks:
    - name: Ensure textproc/jq is installed
      pkgng:
        name: textproc/jq
        state: present
        cached: true
...
