# consul client
---
- name: Consul clients
  hosts: freebsd_consul_clients
  gather_facts: true  # Needed for substituting template vars
  tasks:
    - name: Ensure client is configured
      ansible.builtin.template:
        src: Files/{{ item }}.tpl
        dest: /usr/local/etc/consul.d/{{ item }}
        mode: '0644'
      loop:
        - CONSUL_client.json
      notify: Handler restart consul

  handlers:
    - name: Handler restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
