# consul client
---
- name: Ensure consul client is unconfigured
  hosts: freebsd_consul_clients
  tasks:
    - name: unconfigure consul client
      ansible.builtin.file:
        path: /usr/local/etc/consul.d/CONSUL_client.json
        state: absent
      notify:
        - Handler restart consul

  handlers:
    - name: Handler restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
