# The consul service
---
- hosts: freebsd
  gather_facts: false
  tasks:
    - name: start and enable the service
      ansible.builtin.service:
        name: consul
        state: started
        enabled: true
...
