# consul service checks
---
- name: Ensure consul service checks are deployed
  hosts: freebsd
  tasks:
    - name: Ensure service checks are configured
      ansible.builtin.template:
        src: Files/{{ item }}
        dest: /usr/local/etc/consul.d/{{ item }}
        mode: '0644'
      loop:
        - service_checks.json
      notify: Handler restart consul

  handlers:
    - name: Handler restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
