# consul client
---
- hosts: freebsd_consul_clients
  gather_facts: true  # Needed for substituting template vars
  tasks:
    - name: configure client
      ansible.builtin.template:
        src: Files/{{ item }}.tpl
        dest: /usr/local/etc/consul.d/{{ item }}
        mode: 0644
      loop:
        - CONSUL_client.json
      notify: restart consul

  handlers:
    - name: restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
