# The consul service
---
- name: Ensure consul service is running
  hosts: freebsd
  gather_facts: false
  tasks:
    - name: Start and enable the service
      ansible.builtin.service:
        name: consul
        state: started
        enabled: true
...
