# The consul package
---
- hosts: freebsd
  gather_facts: false
  tasks:
    - name: stop and disable the service
      service:
        name: consul
        state: stopped
        enabled: no
    - name: deinstall consul
      community.general.pkgng:
        name: sysutils/consul
        state: absent
        cached: yes
    - name: remove the config dir
      ansible.builtin.file:
        path: /usr/local/etc/consul.d
        state: absent
    - name: remove the data dir
      ansible.builtin.file:
        path: /var/db/consul
        state: absent
...
