# The consul package
---
- hosts: freebsd
  gather_facts: false
  tasks:
    - name: install sysutils/facter  # cfacter (variables used in templates)
      pkgng: name=sysutils/facter state=present cached=yes
    - name: install consul
      pkgng: name=sysutils/consul state=present cached=yes
    - name: create the config dir
      file: state=directory path=/usr/local/etc/consul.d
- import_playbook: consul_service.yaml
