# consul service checks
---
- hosts: freebsd
  tasks:
  - template:
      src: Files/service_checks.json
      dest: /usr/local/etc/consul.d/service_checks.json
    notify:
      - restart consul

  handlers:
    - name: restart consul
      service: name=consul state=restarted
