# consul service checks
---
- hosts: freebsd
  tasks:
    - name: configure service checks
      ansible.builtin.template:
        src: Files/{{ item }}
        dest: /usr/local/etc/consul.d/{{ item }}
        mode: 0644
      loop:
        - service_checks.json
      notify: restart consul

  handlers:
    - name: restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
