# consul client
---
- hosts: freebsd_consul_clients
  tasks:
  - file:
      path: /usr/local/etc/consul.d/CONSUL_client.json
      state: absent
    notify:
      - restart consul

  handlers:
    - name: restart consul
      service: name=consul state=restarted
