# consul service checks
---
- name: Ensure consul service checks are unconfigured
  hosts: freebsd
  tasks:
    - name: Unconfigure service
      ansible.builtin.file:
        path: /usr/local/etc/consul.d/service_checks.json
        state: absent
      notify:
        - Handler restart consul

  handlers:
    - name: Handler restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
