# consul server
---
- hosts: freebsd_consul_servers
  tasks:
    - name: unconfigure consul server
      ansible.builtin.file:
        path: /usr/local/etc/consul.d/CONSUL_server.json
        state: absent
      notify:
        - restart consul

  handlers:
    - name: restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
