# consul client
---
- hosts: freebsd_consul_clients
  gather_facts: true  # Needed for substituting template vars
  tasks:
  - template:
      src: Files/CONSUL_client.json.tpl
      dest: /usr/local/etc/consul.d/CONSUL_client.json
    notify:
      - restart consul

  handlers:
    - name: restart consul
      service: name=consul state=restarted
