# consul server
---
- name: Ensure consul servers are unconfigured
  hosts: freebsd_consul_servers
  tasks:
    - name: Unconfigure consul server
      ansible.builtin.file:
        path: /usr/local/etc/consul.d/CONSUL_server.json
        state: absent
      notify:
        - Handler restart consul

  handlers:
    - name: Handler restart consul
      ansible.builtin.service:
        name: consul
        state: restarted
...
