# The consul package
---
- name: Ensure consul is deployed
  hosts: freebsd
  gather_facts: false
  tasks:
    - name: Install sysutils/facter  # cfacter (variables used in templates)
      community.general.pkgng:
        name: sysutils/rubygem-facter
        state: present
        cached: true
    - name: Install consul
      community.general.pkgng:
        name: sysutils/consul
        state: present
        cached: true
    - name: Create the config dir
      ansible.builtin.file:
        state: directory
        path: /usr/local/etc/consul.d
        mode: 0755
- name: Import consul_service.yaml
  import_playbook: consul_service.yaml
...
