# The py-yamllint package
---
- name: Ensure py-yamllint is installed
  hosts: ansible_host
  gather_facts: false
  tasks:
    - name: Install devel/py-yamllint
      portinstall:
        name: devel/py-yamllint
        state: present
        use_packages: false
      check_mode: false
...
