---
- hosts: ansible_host
  gather_facts: false
  tasks:
  - name: remove port py-pathspec
    file: path=/usr/ports/python/py-pathspec   state=absent
  - name: adapt /usr/ports/textproc/Makefile, though it may be naughty
    blockinfile:
      path: /usr/ports/textproc/Makefile
      insertbefore: .include <bsd.port.subdir.mk>
      block: |
          SUBDIR += py-yamllint
          SUBDIR += py-pathspec
      state: absent
  - name: check if py-yamllint is in index file,
          the ansible portinstall module requires that
    shell: portsdb textproc/py-yamllint > /tmp/py-yamllint_found
  - name: if in index file, rebuild the index file.
          Rebuilding may take a while.
    shell: if grep textproc/py-yamllint /tmp/py-yamllint_found; then portsdb -uU; fi
