# The py-yamllint package + deps
---
- name: Ensure py-yamllint package is deinstalled
  hosts: ansible_host
  gather_facts: false
  tasks:
    - name: Deinstall devel/py-yamllint
      community.general.pkgng:
        name: devel/py-yamllint
        state: absent
        cached: true
    - name: Deinstall python/py-pathspec
      community.general.pkgng:
        name: devel/py-pathspec
        state: absent
        cached: true
...
