# The py-yamllint package + deps
---
- hosts: ansible_host
  gather_facts: false
  tasks:
    - name: deinstall devel/py-yamllint
      pkgng: name=devel/py-yamllint state=absent cached=yes
    - name: deinstall python/py-pathspec
      pkgng: name=devel/py-pathspec state=absent cached=yes
