---
- hosts: ansible_host
  gather_facts: false
  tasks:
  - name: remove port py-yamllint
    file: path=/usr/ports/textproc/py-yamllint state=absent
  - name: remove port py-pathspec
    file: path=/usr/ports/python/py-pathspec   state=absent
