# The py-yamllint package + deps
---
- hosts: ansible_host
  gather_facts: false
  tasks:
    - name: deinstall devel/py-yamllint
      community.general.pkgng:
        name: devel/py-yamllint
        state: absent
        cached: true
    - name: deinstall python/py-pathspec
      community.general.pkgng:
        name: devel/py-pathspec
        state: absent
        cached: true
...
