# The py-yamllint package
---
- hosts: ansible_host
  gather_facts: false
  tasks:
    - name: install textproc/py-yamllint
      portinstall: name=textproc/py-yamllint state=present use_packages=false
