# The py-yamllint package
# Add it as an unoffical port + install that port
# Btw, this sucks. Better wait till the port is official committed
---
- hosts: ansible_host
  gather_facts: false
  tasks:
    - name: adapt /usr/ports/textproc/Makefile, though it may be naughty
      blockinfile:
        path: /usr/ports/textproc/Makefile
        insertbefore: .include <bsd.port.subdir.mk>
        block: |
            SUBDIR += py-yamllint
            SUBDIR += py-pathspec
    - name: check if py-yamllint is index file,
            the ansible portinstall module wants that
      shell: portsdb textproc/py-yamllint > /tmp/wadie
    - name: if not in index file, rebuild the index file.
            Rebuilding may take a while.
      shell: grep textproc/py-yamllint /tmp/wadie || portsdb -uU
    - name: install textproc/py-yamllint
      portinstall: name=textproc/py-yamllint state=present use_packages=false
