# The py-yamllint package
---
- hosts: ansible_host
  gather_facts: false
  tasks:
    - name: install devel/py-yamllint
      portinstall:
        name: devel/py-yamllint
        state: present
        use_packages: false
      check_mode: false
