# Created by: Andre Rikkert de Koe - ARK-ICT <andre@ark-ict.nl>
# $FreeBSD$

PORTNAME=	pathspec
PORTVERSION=	0.5.6
CATEGORIES=	textproc python
MASTER_SITES=	${MASTER_SITE_CHEESESHOP} \
		http://freebsd.ark-ict.nl/ports/
MASTER_SITE_SUBDIR=	5e/59/d40bf36fda6cc9ec0e2d2d843986fa7d91f7144ad83e909bcb126b45ea88
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	andre@ark-ict.nl
COMMENT=	Utility library for gitignore style pattern matching of file paths

LICENSE=	MPL20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
