# Created by: Andre Rikkert de Koe - ARK-ICT <andre@ark-ict.nl>
# $FreeBSD$

PORTNAME=	pathspec
PORTVERSION=	0.5.5
CATEGORIES=	textproc python
MASTER_SITES=	${MASTER_SITE_CHEESESHOP} \
		http://freebsd.ark-ict.nl/ports/
MASTER_SITE_SUBDIR=9f/fb/5a901a3b1eeebf83af6da74ecca69d7daf5189e450f0f4cccf9c19132651
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	andre@ark-ict.nl
COMMENT=	Utility library for gitignore style pattern matching of file paths

LICENSE=	MPL20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
