# Created by: Andre Rikkert de Koe - ARK-ICT <andre@ark-ict.nl>
# $FreeBSD$

PORTNAME=	pathspec
PORTVERSION=	0.5.6
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP \
		http://freebsd.ark-ict.nl/ports/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	andre@ark-ict.nl
COMMENT=	Utility library for gitignore style pattern matching of file paths

LICENSE=	MPL20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
